var get_lang = function(language) {
    var lang_arr_en = {
        t: 'en',
        btn_up: 'Up!',
        mini: 'Minimize',
        menu: 'Menu',
        close: 'Close',
        full: 'Fullscreen',
        drop_file: 'Drop file hear!',
        drop_append: 'Append file!',
        click_for_open: 'Click for open files',
        playlist: 'Playlist',
        prev: 'Previous',
        play_pause: 'Play / Pause',
        next: 'Next',
        scroll_up: 'Step forward',
        scroll_down: 'Step back',
        mute: 'Mute',
        shuffle: 'Shuffle',
        loop: 'Loop',
        sort: 'Sort by file name/as is',
        read_tags: 'Read all tags',
        playlist_select: 'Select playlist',
        playlist_title: 'Playlist',
        remove_item: 'Remove',
        move_item: 'Move item',
        ctx_open_files: 'Open files',
        ctx_open_folder: 'Open folder',
        ctx_open_folder_sub: 'Open folder with subfolders',
        ctx_open_url: 'Open URL',
        ctx_webui: 'webUI',
        ctx_viz: 'Visualization',
        ctx_cloud: 'Cloud',
        ctx_options: 'Settings',
        ctx_save_vk_track: 'Save current track in VK',
        ctx_save_sc_track: 'Add to favorite SoundCloud!',
        sc_favorite: 'Favorite',
        vk_all: 'My music',
        vk_rec: '[ Suggested music ]',
        vk_pop: '[ Popular music ]',
        no_viz: 'Need install visualizatitoin extension!',
        dialog: {
            back: 'Go Back',
            play_folder: 'Play folder',
            e_url: 'Enter url:',
            e_pl: 'Enter playlist:',
            e_folder: 'Enter folder or files:',
            e_ps: 'Play selected:',
            open: 'Open'
        },
        settings: {
            1: "Language",
            2: 'Player',
            3: 'Clouds',
            4: 'Save',
            5: 'Player settings',
            6: 'Display a notification when changing tracks',
            7: 'Extend the range of the volume scrolls',
            8: 'Show button next / previous track in the notification',
            9: 'Winamp skin (requires restart)',
            10: 'To enable global multimedia keys need to',
            11: 'download the extension',
            12: 'Configure integrated visualization, Winamp',
            13: 'Disable',
            14: 'Spectrogram',
            15: 'Oscillogram',
            16: 'Play/pause',
            17: 'Mute',
            18: 'Shuffle',
            19: 'Loop',
            20: 'Next random visualization',
            21: 'Previous track',
            22: 'Next track',
            23: 'Volume up 10%',
            24: 'Volume down 10%',
            25: 'Scroll back 10 seconds',
            26: 'Scroll up 10 seconds',
            27: 'Menu',
            28: '* For OSX use Command button instead Ctrl.',
            29: 'Hotkeys',
            30: 'Only foreign tracks',
            31: 'Pre-load track',
            32: 'Last.fm scrobbling',
            33: 'Download album cover from Last.fm',
            34: 'WebUI',
            35: 'Port: ',
            36: 'Interface: ',
            37: 'Receive information about the track from Last.fm',
            38: 'Rewrite incorrect tags',
            39: 'Run at startup the player.'
        }
    };
    var lang_arr_ru = {
        t: 'ru',
        btn_up: 'Вверх!',
        mini: 'Свернуть',
        menu: 'Меню',
        close: 'Закрыть',
        full: 'Во весь экран',
        drop_file: 'Перетащи файлы сюда!',
        drop_append: 'Добавить файл!',
        click_for_open: 'Открыть файлы',
        playlist: 'Плейлист',
        prev: 'Предыдущий трек',
        play_pause: 'Воспроизведение / Пауза',
        next: 'Следующий трек',
        mute: 'Приглушить звук',
        scroll_up: 'Шаг вперед',
        scroll_down: 'Шаг назад',
        shuffle: 'Играть вперемешку',
        loop: 'Повтор списка воспроизведения',
        sort: 'Сортировать по имени файла/как есть',
        read_tags: 'Прочитать теги всех файлов',
        playlist_select: 'Выбрать плейлист',
        playlist_title: 'Плейлист',
        remove_item: 'Удалить',
        move_item: 'Передвинуть',
        ctx_open_files: 'Открыть файлы',
        ctx_open_folder: 'Открыть папку',
        ctx_open_folder_sub: 'Открыть папку с подпапками',
        ctx_open_url: 'Открыть URL',
        ctx_webui: 'Веб-интерфейс',
        ctx_viz: 'Визуализация',
        ctx_cloud: 'Облака',
        ctx_options: 'Настройки',
        ctx_save_vk_track: 'Сохранить текущий трек в VK',
        ctx_save_sc_track: 'Добавить в избранное SoundCloud!',
        sc_favorite: 'Избранное',
        vk_all: 'Мои аудиозаписи',
        vk_rec: '[ Рекомендации ]',
        vk_pop: '[ Популярное ]',
        no_viz: 'Требуется расширение для визуализации',
        dialog: {
            back: 'Назад',
            play_folder: 'Воспроизвести директорию',
            e_url: 'Введите URL:',
            e_pl: 'Выберите плейлист:',
            e_folder: 'Выберите директорию или файлы:',
            e_ps: 'Воспроизвести отмеченное:',
            open: 'Открыть'
        },
        settings: {
            1: "Язык / Language",
            2: 'Плеер',
            3: 'Облака',
            4: 'Сохранить',
            5: 'Настройки плеера',
            6: 'Показывать уведомление при смене трека',
            7: 'Расширить область изменения громкости скроллом',
            8: 'Показывать кнопки предыдущий / следующий трек в уведомлении',
            9: 'Winamp скин (требует перезапуск)',
            10: 'Чтобы включить глобальные мультимедиа клавиши нужно',
            11: 'загрузить расширение',
            12: 'Настройки встроенной визуализации Winamp',
            13: 'Отключить',
            14: 'Спектрограмма',
            15: 'Осциллограмма',
            16: 'Пауза/Продолжить воспроизведение',
            17: 'Отключить звук',
            18: 'Включить воспроизведение вперемешку',
            19: 'Включить повтор списка воспроизведения',
            20: 'Следующая случайная визуализация',
            21: 'Предыдущий трек',
            22: 'Следующий трек',
            23: 'Увеличить громкость на 10%',
            24: 'Уменьшить громкость на 10%',
            25: 'Прокрутить назад на 10 секунд',
            26: 'Прокрутить вперед на 10 секунд',
            27: 'Меню',
            28: '* Для OSX вместо Ctrl используется Command.',
            29: 'Горячие клавиши',
            30: 'Только зарубежные треки',
            31: 'Предзагружать трек',
            32: 'Last.fm скробблинг',
            33: 'Загружать обложки альбомов с Last.fm',
            34: 'Веб-интерфейс',
            35: 'Порт: ',
            36: 'Интерфейс: ',
            37: 'Получать информацию о треке с Last.fm',
            38: 'Переписывать неправильные теги',
            39: 'Запустить при включении плеера'
        }
    };
    if (window.options === undefined) {
        delete window.get_lang;
    }
    var lang = language || window._language;
    if (lang === undefined) {
        lang = 'en';
        /**
         * @namespace chrome.i18n.getMessage
         */
        if (chrome.i18n.getMessage("lang") === 'ru') {
            lang = 'ru';
        }
    }
    if (lang === 'ru') {
        window._lang = lang_arr_ru;
    } else {
        window._lang = lang_arr_en;
    }
};
get_lang();